### ISSUE TITLE
Wireframe of UI for Hook

### ISSUE THREAD

**Issue by PonteIneptique** [Capitains/Hook#1]
![wireframe](https://cloud.githubusercontent.com/assets/1929830/8952973/e14a4802-35db-11e5-9bbc-726784108a03.png)

**Comment by PonteIneptique** [comment]
@balmas @srdee I think this is the UI we would need, I might have forgotten something. Maybe Lisa should also participate in this discussion ?

**Comment by PonteIneptique** [comment]
Note that this would be milestone 1 for Hook : being able to test and customize test.
**Milestone 1** can also integrates viz / searches of text (Not sure but well, could be 1.2 or 2)
**Milestone 2** would be "Enabling Metadata pulling and merging" (I'll probably not be able to do that myself in the time I have before PhD. Will obviously be happy to help through)

**Comment by srdee** [comment]
That looks great! I for sure want the testing to be in a decent state before I leave. The UI/viz probably won't be, but potentially could be a project for a Uni Leipzig CS student. I'm going to cite this issue on this page: https://github.com/PerseusDL/tei-conversion-tools/wiki/Helping,-Entry-Points-for-Contributing
