### ISSUE TITLE
trigger on commit as well as PR?

### ISSUE THREAD

**Issue by balmas** [Capitains/Hook#38]
sorry if I've asked this before ... hook currently only triggers on PR correct? If so, would it be hard to add a configurable option to allow it to trigger on commit as well?

**Comment by PonteIneptique** [comment]
![hook](https://cloud.githubusercontent.com/assets/1929830/10782050/75d052a6-7d4d-11e5-8b4a-4245704d03ab.png)

This feature is already available. Just need to uncheck "Master & PR :)
