### ISSUE TITLE
"Run" button doesn't work on http://ci.perseids.org/

### ISSUE THREAD

**Issue by sonofmun** [Capitains/Hook#44]
I have added a new repository that I want to have checked (https://github.com/OpenGreekAndLatin/csel-dev).  I have added it and then clicked on the red power button.  Now I have a "Run" button, but when I click it, nothing happens.  Then, if I right-click and open it in another tab, the new tab shows an internal server error.

```
Internal Server Error

The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at webmaster@localhost to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log.

Apache/2.4.7 (Ubuntu) Server at ci.perseids.org Port 80
```

The following image is what the Hook webpage looks like when I click the "Run" button.

![image](https://cloud.githubusercontent.com/assets/3787067/11117147/9da28c7c-8937-11e5-860c-6a592af873cb.png)

**Comment by PonteIneptique** [comment]
This won't run. This bug has been discovered (instead of an error, it 
won't run). You do not follow the data/textgroup/work folder scheme.

**Comment by sonofmun** [comment]
Oh, I know that it doesn't follow the correct scheme.  But we will be 
changing that slowly but surely and I just wanted make sure that we have 
it in the pipeline to run tests when we do change the structure (which 
might even be today).

On 12.11.2015 12:25, Thibault Clérice wrote:
> This won't run. This bug has been discovered (instead of an error, it
> won't run). You do not follow the data/textgroup/work folder scheme.
>
> On 12/11/2015 12:21, sonofmun wrote:
> >
> > I have added a new repository that I want to have checked
> > (https://github.com/OpenGreekAndLatin/csel-dev). I have added it and
> > then clicked on the red power button. Now I have a "Run" button, but
> > when I click it, nothing happens. Then, if I right-click and open it
> > in another tab, the new tab shows an internal server error.
> >
> > |Internal Server Error The server encountered an internal error or
> > misconfiguration and was unable to complete your request. Please
> > contact the server administrator at webmaster@localhost to inform them
> > of the time this error occurred, and the actions you performed just
> > before this error. More information about this error may be available
> > in the server error log. Apache/2.4.7 (Ubuntu) Server at
> > ci.perseids.org Port 80 |
> >
> > The following image is what the Hook webpage looks like when I click
> > the "Run" button.
> >
> > image
> > 
> <https://cloud.githubusercontent.com/assets/3787067/11117147/9da28c7c-8937-11e5-860c-6a592af873cb.png>
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/Capitains/Hook/issues/44>.
> >
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/Capitains/Hook/issues/44#issuecomment-156078753>.
>

-- 
Matthew Munson
Researcher
Alexander von Humboldt Chair of Digital Humanities
Universität Leipzig, Institut für Informatik
Augustusplatz 10, 04109 Leipzig
Deutschland

**Comment by sonofmun** [comment]
So, if I understand correctly, the problem is with the repository and that it doesn't have the correct folder structure.  If so, then Hook should at least give an indication that this is why the tests are not running.  Or is this a problem with Hook?

**Comment by PonteIneptique** [comment]
There is potentially two bugs there. I just opened another issue for this one.
