### ISSUE TITLE
PR & Master Only is not work anymore.

### ISSUE THREAD

**Issue by PonteIneptique** [Capitains/Hook#49]
- **Reproducibility :** 100%
- **Set up :**
  - Add a repository
  - Click on master and pr only
  - Push to third branch
  - Test runs
- **Expected output :**
  - Test does not run

**Comment by sonofmun** [comment]
This does not seem to be a problem with csel-dev.  When we push to a different branch, no Hook tests run.  When we initiate a pull request for that non-master remote branch, Hook then runs.  And then it runs again as soon as someone approves the PR.

**Comment by PonteIneptique** [comment]
This is then the normal behaviour :)
Travis does the same.

**Comment by sonofmun** [comment]
It looks like we are actually also having the problem with csel-dev.  If you look at the tests here (http://ci.perseids.org/repo/OpenGreekAndLatin/csel-dev), it looks like it is running the tests when changes are first pushed to a branch that isn't master, then again when the pull request is made, and a third time when the pull request is merged.

**Comment by PonteIneptique** [comment]
PR + Master is totally normal. The other one is not. I'll have a bug check when we do the streaming code session
