### ISSUE TITLE
available in inventory failed result

### ISSUE THREAD

**Issue by lcerrato** [Capitains/Hook#55]
I had the same "Available in inventory failed" result as below but I believe that my cts.xml work level file has all of the info that was added to correct the issue.

https://github.com/OpenGreekAndLatin/csel-dev/issues/121

Please point me to any doc on this.

**Comment by balmas** [comment]
lisa, one thing to check would be whether the urn in the @n attribute of the edition or translation div matches the filename and the metadata in the __cts__.xml.  If it doesn't it will cause this error.

**Comment by lcerrato** [comment]
That's where I've been looking, but so far I can't spot the problem. (I may not be able to see it myself at this point). Comparing with other files that do work and I'm seeing more/less info the cts.xml files but so far adding and subtracting this has made no difference.

**Comment by lcerrato** [comment]
Ugh. Fixed one file but not the other. The urn had urn:ti instead of urn:cts.
Still have the error for the greek file, though.

**Comment by balmas** [comment]
I think the problem is this:

`<div type="edition" xml:lang="grc" n="urn:cts:file:tlg0013.tlg001.perseus-grc2.xml">`

There shouldn't be any xml in the urn in the n attribute. And the namespace is also weird.

` <div type="edition" xml:lang="grc" n="urn:cts:greekLit:tlg0013.tlg001.perseus-grc2">`

**Comment by lcerrato** [comment]
this is the type of thing I wouldn't be seeing at this point!
onto more work, but I'll check this with the next round
