### ISSUE TITLE
Should Hook be checking the xml declarations?

### ISSUE THREAD

**Issue by sonofmun** [Capitains/Hook#56]
I accidentally removed all the xml declaration from csel-dev, i.e., 

```
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="http://www.stoa.org/epidoc/schema/latest/tei-epidoc.rng" schematypens="http://relaxng.org/ns/structure/1.0"?>'
```

and all the files still passed.  I have added the declarations back in and they still pass.  So the question: should Hook be checking to make sure these lines are there?

**Comment by PonteIneptique** [comment]
@sonofmun Could you move that to HookTest/issues ?
