### ISSUE TITLE
Hook not responding?

### ISSUE THREAD

**Issue by lcerrato** [Capitains/Hook#57]
Doesn't seem to be building.

**Comment by PonteIneptique** [comment]
The issue seem to be on homer side. Probably a reboot or something broke the service...

**Comment by balmas** [comment]
I have setup an alternate HookTest/HookWorker environment on the perseids build server and have switched Hook over to use it.  We should discuss this when I'm at Tufts tomorrow.

**Comment by lcerrato** [comment]
now that I know the server's name is Homer this makes a lot more sense! 
d'oh!
