### ISSUE TITLE
New comment format for PR 

### ISSUE THREAD

**Issue by PonteIneptique** [Capitains/Hook#62]
Hey @sonofmun @balmas , what do you think of this format of comment on Pull Request and Commit : 

------------------

### Global

| Changed          |   Status |
|:-----------------|---------:|
| `coverage`       |    -0.01 |
| `metadata_total` |     5    |
| `nodes_count`    |   -44    |
| `texts_passing`  |     1    |

### Words

| Changed   |   Status |
|:----------|---------:|
| `eng`     |       +1 |
| `lat`     |      -11 |

### Units

| Changed                                           | Status   |
|:--------------------------------------------------|:---------|
| `data/tlg0015/__cts__.xml`                        | Deleted  |
| `data/tlg0015/tlg002/__cts__.xml`                 | New      |
| `data/tlg0015/tlg001/__cts__.xml`                 | Failed   |
| `data/tlg0015/tlg001/tlg0015.tlg001.opp-grc1.xml` | Passing  |
| `data/tlg0015/tlg002/__cts__.xml`                 | Failed   |

**Comment by PonteIneptique** [comment]
I have used table but maybe list would be enough for some of these ?

**Comment by PonteIneptique** [comment]
This kind of feedback might really change the needs to go read everytime the output of hooktest :)

**Comment by balmas** [comment]
I think it's awesome.

**Comment by PonteIneptique** [comment]
Good. It will be only available when you use HookUi obviously but :)
